# Generated by Django 3.2.13 on 2022-05-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[(1, 'Nairobi'), (2, 'Nyanza'), (3, 'Central'), (4, 'Coast'), (5, 'Eastern'), (6, 'North Eastern'), (7, 'Western'), (8, 'Rift Valley')], max_length=255)),
                ('kgs', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.customer')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paying_number', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[(1, 'Cash'), (2, 'Mpesa')], max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.customer')),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.bill')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.orders')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customerbill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalApp.customerbill'),
        ),
    ]
