# Generated by Django 4.2 on 2023-12-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('secondary_phone', models.CharField(default=0, max_length=255)),
                ('alternative_phone', models.CharField(default=0, max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[(1, 'Nairobi'), (2, 'Nyanza'), (3, 'Central'), (4, 'Coast'), (5, 'Eastern'), (6, 'North Eastern'), (7, 'Western'), (8, 'Rift Valley')], max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Call Back',
                'verbose_name_plural': 'Mpesa Call Backs',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('caller', models.TextField()),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Call',
                'verbose_name_plural': 'Mpesa Calls',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('type', models.TextField()),
                ('reference', models.TextField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.TextField()),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('kgs', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=255)),
                ('transporters', models.CharField(choices=[(1, 'Others'), (2, 'In-house')], max_length=255)),
                ('rider', models.CharField(default=0, max_length=255)),
                ('vat', models.CharField(default=0, max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('farmer_price', models.CharField(default=180, max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('rice_type', models.CharField(choices=[(1, 'Pishori'), (2, 'Komboka')], max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.customer')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RicePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paddy_rice', models.CharField(max_length=250)),
                ('paddy_date', models.DateField()),
                ('paddy_komboka', models.CharField(max_length=250)),
                ('komboka_date', models.DateField()),
                ('pishori', models.CharField(max_length=250)),
                ('pishori_date', models.DateField()),
                ('komboka', models.CharField(max_length=250)),
                ('rice_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('rice_type', models.CharField(choices=[(1, 'Pishori'), (2, 'Komboka')], max_length=255)),
                ('kgs', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paying_number', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'Bank'), (4, 'Barter Trade'), (5, 'Promo'), (6, 'Compensation'), (7, 'Top-up')], max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.customer')),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_id', models.CharField(max_length=255)),
                ('kgs', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('packaging', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('transport', models.CharField(max_length=255)),
                ('rider', models.CharField(max_length=255)),
                ('vat', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rice_type', models.CharField(choices=[(1, 'Pishori'), (2, 'Komboka')], max_length=255)),
                ('in_stock', models.CharField(max_length=255)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.bill')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.orders')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='customerbill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApp.customerbill'),
        ),
    ]
