# Generated by Django 4.2 on 2024-07-18 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0005_remove_invoice_name_remove_invoice_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pythonApp.region'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='rice_type',
            field=models.CharField(choices=[(1, 'Pishori'), (2, 'Komboka'), (3, 'Brown')], max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(blank=True, default=9, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
