# Generated by Django 4.2 on 2024-07-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApp', '0007_alter_orders_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alternative_phone',
        ),
    ]
